### ISSUE TITLE
The highlight or "recipe give" is wrong

### ISSUE THREAD

**Issue by Panossa** [42iscool42/MCC#10]
Because "give" is also a command, "recipe give" gets wrong color coding. See "recipe take" for the right color coding.

**Comment by 42iscool42** [comment]
This has been fixed in the most recent update.

**Comment by Moesh** [comment]
Reopening at present in v1.3.17, we missed take.

![image](https://user-images.githubusercontent.com/4852592/27989140-8d14de66-6408-11e7-9f31-55280f391655.png)

**Comment by 42iscool42** [comment]
Recipe take has now been added, a release will be coming later today with the change.
