### ISSUE TITLE
/xp and its arguments do not have highlighting.

### ISSUE THREAD

**Issue by Sybillian** [42iscool42/MCC#11]
"xp" and "0L" do not have highlighting, though /xp does have an autocomplete.

**Comment by Moesh** [comment]
This must've been introduced with a newer update, we were highlighting xp correctly before the 1.12 update, must be my fault. looking into it now.

![image](https://user-images.githubusercontent.com/4852592/27989201-1ec9de64-640a-11e7-9d01-90146e00ac6d.png)

**Comment by 42iscool42** [comment]
This and the fact that the negative sign in front of the number wasn't being highlighted properly will be coming out in the release later today.
