### ISSUE TITLE
(At least) the function command has not perfect highlighting

### ISSUE THREAD

**Issue by Panossa** [42iscool42/MCC#13]
Try this command:
function something:giveSomething
Since "give" is a command the "Something" in the end is not highlighted.
(Using v1.3.18)

**Comment by 42iscool42** [comment]
Actually, it is not working because the S in Something is capitalized.  The function names and file locations have to be in all lowercase letters.

**Comment by Panossa** [comment]
Well I work in my projects with function names in camelCase so I need the highlight. Sure, MC converts them to lowercase, but I'm used to camelCase.

**Comment by Moesh** [comment]
They are converted to lowercase_and_underscored as it is the standard for all world/resource pack files in Minecraft. It may be valid and handled, but MCC strictly highlights what is considered correct. Closing issue.
