### ISSUE TITLE
Namespaces within advancement commands are not highlighted.

### ISSUE THREAD

**Issue by Sybillian** [42iscool42/MCC#15]
![advancement_bug](https://user-images.githubusercontent.com/12521221/28041770-4554f5be-6590-11e7-839c-3938d48434d8.PNG)

In theory this should inherit the same highlighting that the function command uses.

![proper_highlight](https://user-images.githubusercontent.com/12521221/28041801-608f75a2-6590-11e7-9989-6fe5f451b543.PNG)

**Comment by Panossa** [comment]
Good catch. No idea how I missed that xD

**Comment by 42iscool42** [comment]
This is fixed in the 1.13 beta version.
