### ISSUE TITLE
NBT tag types are handled incorrectly in some cases.

### ISSUE THREAD

**Issue by Panossa** [42iscool42/MCC#16]
See attached image.
![snap_2017 07 11_01h18m24s_003_](https://user-images.githubusercontent.com/23323875/28044296-db15e37e-65d6-11e7-8dc7-2f1df2eaf17e.png)

**Comment by Panossa** [comment]
Update: Slot:1b, Slot:2b and so on don't get highlighted. Only something that can only be 1 or 0 is highlighted with a 'b' following it.

**Comment by Panossa** [comment]
Update 2: Maxaxik thinks every int can be filled up with an "s" afterwards and still gets highlighted. Like in Duration.

**Comment by Panossa** [comment]
Update 3: Maxaxik found a lot more of those via ChunkFormat.
See attached image:
![snap_2017 07 12_00h20m19s_003_](https://user-images.githubusercontent.com/23323875/28093514-e9462a78-6697-11e7-9a2e-f706a930a9be.png)

**Comment by Panossa** [comment]
Two more:

	testfor @s {UUIDLeast:2L}
	testfor @s {UUIDMost:2L}

**Comment by 42iscool42** [comment]
All b, s, and d issues have been fixed the [I;(num)] syntax is a work in progress.

**Comment by 42iscool42** [comment]
The integer array syntax has now been added.  It will be available with the next release.
