### ISSUE TITLE
Dash character interrupts highlighting of function names and namespaces.

### ISSUE THREAD

**Issue by Sybillian** [42iscool42/MCC#26]
Including a "-" character in the name of a function's name or namespace will interrupt and break highlighting, respectively, despite both working properly in Minecraft.

![dashbug](https://user-images.githubusercontent.com/12521221/28107354-1528ec56-66ad-11e7-88b1-da32b71c2d14.PNG)

**Comment by Panossa** [comment]
I think the answer to that will be the same as here: https://github.com/42iscool42/MCC/issues/13

**Comment by Sybillian** [comment]
#13 is invalid due to the fact that camelCase doesn't work on all operating systems and therefore is not supported. kebab-case works perfectly fine universally, though.

**Comment by Moesh** [comment]
Marked as enhancement and a bug as this was as designed, but kebab-case meets our standards.
