### ISSUE TITLE
Particle command highlighting is a bit broken.

### ISSUE THREAD

**Issue by Panossa** [42iscool42/MCC#27]
As seen in this image:
![snap_2017 07 18_00h35m23s_002_](https://user-images.githubusercontent.com/23323875/28292797-141fa4be-6b51-11e7-8163-68c7a0526a05.png)

Code sample:
```particle smoke ~ ~ ~ 0.1 3 0.1 0.1 100```

**Comment by Moesh** [comment]
smoke and all numbers should be highlighted

**Comment by Panossa** [comment]
Update:
This is how it looks with mcfunction highlighting:
![snap_2017 07 22_18h06m47s_004_](https://user-images.githubusercontent.com/23323875/28492723-a238b032-6f08-11e7-8baf-f5e1f18fc7d1.png)
And this is with mcc highlighting:
![snap_2017 07 22_18h06m58s_005_](https://user-images.githubusercontent.com/23323875/28492725-a75ba182-6f08-11e7-8030-6c486a27c459.png)
