### ISSUE TITLE
Adopting new Smelt behavior

### ISSUE THREAD

**Issue by Moesh** [42iscool42/MCC#3]
Smelt has a new addition for defining Command Block types, as well as variable handlers.

> The right angle bracket > trigger is for JSON properties. 
> A valid JSON string (in curly {} brackets) is then used to set properties for the commands.

`>{ "type":"repeating","auto":true, "conditional":true, "executeAs":"@a[name=whatever]", "markerTag";"NameName" }`

While this uses JSON, the behavior controls the type of command blocks being placed.

I think we should highlight the `>{}` to as either a command or a support type.

I'm leaning towards support type, since it affects every command to follow until a new line of command blocks is determined, but I'm not sure.

More info here: http://smelt.gnasp.com/syntax.html

**Comment by 42iscool42** [comment]
I think it would be a good idea to include the >{} notation because it would allow the smelt commands to be isolated from the regular json in the code and we would be able to provide more specific syntax highlighting for smelt.

**Comment by Moesh** [comment]
That sounds great. I tried taking a swing at this, but got confused quickly. Would you be able to walk me through it?

**Comment by 42iscool42** [comment]
Yeah, I'm away this week but I should be free next week.

**Comment by GnaspGames** [comment]
Also, there is a new *variables* feature: http://smelt.gnasp.com/syntax.html#variables

Would it be possible to add highlighting to how they are declared and used? 

Example:

```
    $name=Gnasp
    $nameAndTitle=Mr ${name}
    
    /say Good day ${nameAndTitle}!
```

Output: `[@] Good day Mr Gnasp!`

**Comment by 42iscool42** [comment]
That should be pretty easy to implement

**Comment by GnaspGames** [comment]
Sorry to add more; but "repeating-chain" and "impulse-chain" are now valid on the JSON properties

Example:

```
# CHECK TIMER
>{"type":"repeating-chain", "auto":true}
	/worldborder get
	/stats block ~-1 ~ ~ set QueryResult @e[type=ArmorStand,name=SYSTEM] timer 
	/scoreboard players remove @e[type=ArmorStand,name=SYSTEM] timer 1000000 
```

**Comment by 42iscool42** [comment]
We will definitely include that when we update the syntax.

**Comment by 42iscool42** [comment]
The newest version now includes smelt's json and variables.
