### ISSUE TITLE
[Idea] Adding autocomplete to gamerule command

### ISSUE THREAD

**Issue by Panossa** [42iscool42/MCC#30]
If you type `gamerule doDay..` in MC you can autocomplete it with TAB. Would be cool if the highlighter could do the same. Maybe even in other cases such as `/summon Min[ecart]`

**Comment by Moesh** [comment]
Holding back on this until Minecraft 1.13--the other issues are more important.

**Comment by MattCM** [comment]
Just wondered if this will be worked in as its pretty cool if it did
