### ISSUE TITLE
Missing highlighting for AT LEAST the number in scoreboard commands.

### ISSUE THREAD

**Issue by Panossa** [42iscool42/MCC#31]
Example Command:
`scoreboard players add @a temp 1`
Neither "temp" is highlighted as something special (like e.g. in [tag=something] the `something` is highlighted). Nor the 1 in the end of the line. Normally at least numbers are highlighted.

**Comment by Moesh** [comment]
temp not being highlighted is as signed. This signifies this is an user-controlled variable.

The numbers are supposed to be highlighted. Thanks for this.
