### ISSUE TITLE
New Score Selector Syntax [Addition]

### ISSUE THREAD

**Issue by VexSpectre** [42iscool42/MCC#37]
New score selector syntax on 1.13 is `@a[scores={scoreTest=1}]`. Please add support to the new syntax.

**Comment by 42iscool42** [comment]
I am currently reworking the entire highlighting system for 1.13 and this will be fixed once that version is complete.

**Comment by 42iscool42** [comment]
If you change your file extensions to .mcc13 it will highlight commands in that file using the 1.13 entity highlighting
