### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by nightlibra** [42iscool42/MCC#39]
1. Both
2. Error loading syntax file "Packages/MinecraftCommandCode/Minecraft Function.tmLanguage
3. 
![error](https://user-images.githubusercontent.com/33603069/38782832-3236c3d2-40c7-11e8-9232-4e250a56c084.png)

4. There is no code, this error appears whenever I open Sublime text 3.
5. Mark the issue as a bug and submit it

**Comment by 42iscool42** [comment]
This problem has been fixed in the newest release.  It may take some time for package control to notice the new version so be patient.
