### ISSUE TITLE
/stats block and /stats entity autocompletions both lack a closing square bracket in [objective]

### ISSUE THREAD

**Issue by Sybillian** [42iscool42/MCC#4]
Using the autocomplete function for `stats block` and `stats entity` output the following, respectively:

/stats block <x> <y> <z> <clear|set> <stat> [selector] [objective
/stats entity <selector> <clear|set> <stat> [selector2] [objective

**Comment by 42iscool42** [comment]
This has been fixed in the newest released. Thanks for reporting it.
