### ISSUE TITLE
1.13 Parsing 

### ISSUE THREAD

**Issue by NotJeven** [42iscool42/MCC#41]
Occurs when using ```#use 1.13 parsing```

Some commands are not being recognized as valid? 

![image](https://user-images.githubusercontent.com/15371999/42900823-deb4ea66-8a97-11e8-8f3d-718e65fc914c.png)

Caused by any new (1.13) command:
- tag
- execute
- team
- etc

**Comment by k0nker** [comment]
I'm having this same issue with a lot of scoreboard objectives and some particles and playsounds.  It highlights them like the above image.  Using the Nate The Plate edition that came with MCC.

**Comment by NotJeven** [comment]
Well that's mildly embarrassing!

The latest update fixed the most persistent issues I had (ones that also occurred on the default themes), but I am still having a few problems with the [Boron](https://packagecontrol.io/packages/Boron%20Color%20Scheme) theme. I Also made sure everything ran without error in Minecraft this time :P:

![image](https://user-images.githubusercontent.com/15371999/43375147-494885da-9381-11e8-9392-c4dd518c06af.png)

**Comment by 42iscool42** [comment]
The newest release should fix this problem, but you'll need to delete the old generated color scheme in order for MCC to reconvert it.  For Windows open the file explorer, type %appdata%\Sublime Text 3\Packages\MCC\ModifiedColorSchemes and hit enter.  Then delete the file called boron.tmTheme.

**Comment by NotJeven** [comment]
Returns an error upon reloading the theme.

```error: MCC couldn't find a matching scope for mccliteral```

I have a custom install so my parent directories differ, not sure if they are required to be specific.

**Comment by 42iscool42** [comment]
This is fixed in the current update.  You'll need to delete the scheme again, but I tested it on my machine and it worked with this color scheme.
