### ISSUE TITLE
instant_damage and instant_health are marked as invalid syntax

### ISSUE THREAD

**Issue by matistis** [42iscool42/MCC#42]
Version: MCFunction (Haven't tested Marshal Command Code)
Issue: instant_damage and instant_health are marked as invalid syntax. To recreate, simply do `effect give @a minecraft:instant_damage` or `effect give @a minecraft:instant_health`.
Screenshot showing that instant health and damage don't work but other effects such as night vision do: ![capture](https://user-images.githubusercontent.com/27899617/43487194-8aa47d44-94db-11e8-889d-57def7fd60a9.PNG)

**Comment by 42iscool42** [comment]
Fixed in the latest release.
