### ISSUE TITLE
The highlighter marks negative numbers in "scores" selector array as incorrect.

### ISSUE THREAD

**Issue by Hugman76** [42iscool42/MCC#43]
I don't know how to check the version, but this is the latest version according to sublime. (Marshal)

As title says. Try writing `execute as @a[scores={Timer=-1}] at @s run say test` and you will see `-1` in red.
![capture5](https://user-images.githubusercontent.com/36963654/43594524-b68a7ae4-967a-11e8-99c1-bca3141307b3.PNG)

**Comment by 42iscool42** [comment]
Fixed in the latest release.
