### ISSUE TITLE
Marked as invalid syntax with quote

### ISSUE THREAD

**Issue by PlusQueParfa** [42iscool42/MCC#44]
Version : Marshal Command Code
Issue : selector with quote (@a[name="playername"] are marked invalid syntax
To recreate simply do `execute at @a[name="playername"] run say test`

Screenshot :
![2018-08-06_11-41-29_sublime_text](https://user-images.githubusercontent.com/42135943/43709649-a9d45194-996d-11e8-84d8-981615d67656.png)

**Comment by 42iscool42** [comment]
Fixed in the latest release.
