### ISSUE TITLE
Block-related commands need highlighting for wordy blockstates

### ISSUE THREAD

**Issue by Moesh** [42iscool42/MCC#5]
http://minecraft.gamepedia.com/Block_states

We can now use
`setblock ~ ~ ~ minecraft:furnace facing=west` for all specific blocks.

The stretch goal is to have verification for every blockstate for every block. I think we should start with getting all the keywords and values into our support.

Some of this stuff may be able to be pulled across from what we have in our NBT highlighting.

**Comment by Panossa** [comment]
Stop. The description does not fit to the (new) title in any way. Blockstates are what is used outside of NBT tag lists (which is what entitydata and blockdata are).
Please change the title pack and open a new issue for entitydata/blockdata highlighting. Those are two completely different things.

**Comment by Moesh** [comment]
I changed the title to fit this particular description. The goal here is to gather all the keywords and states, then put them into our system. The title matches the description. If there is another issue, please be more explicit, or log it yourself. Thanks.

**Comment by 42iscool42** [comment]
This has been fixed in the beta 1.13 version.
