### ISSUE TITLE
Syntax uses incorrect or missing objective criteria

### ISSUE THREAD

**Issue by DerpNerb** [42iscool42/MCC#51]
**Version:**  Marshal Command Code v2.0.10
**Description:** Some scoreboard criteria are not recognized by the syntax. In the screenshots hereunder the pink ones are the ones not being recognized.
**Screenshots:**
![image](https://user-images.githubusercontent.com/39121384/45743362-21eaf880-bbfc-11e8-8b10-8c2a5a91eae7.png)
![image](https://user-images.githubusercontent.com/39121384/45743415-3d560380-bbfc-11e8-9b48-d4c4059a7604.png)
![image](https://user-images.githubusercontent.com/39121384/45743459-58287800-bbfc-11e8-8362-50a7809a06fd.png)

**Comment by 42iscool42** [comment]
This has now been fixed in the newest release.  One important thing to note is that teamkill and killbyteam use the syntax teamkill.[color] and killbyteam.[color].  There is a period, not a space, between the main criteria and the color.
