### ISSUE TITLE
Syntax too strict/incorrect with nbt data

### ISSUE THREAD

**Issue by DerpNerb** [42iscool42/MCC#52]
**Version:** Marshal Command Code v2.0.10
**Description:** The syntax only allows nbt data if there is a certain character behind it, like: onGround:1 isn't allowed, but onGround:1b is. This should be changed, because they both work in the game.
 
Also, the Age tag on an area_effect_cloud doesn't work ingame when there is a 's' behind it, but it does work without. idk why this is the case in Minecraft, but I do know that the syntax suggests the wrong way of doing it. 
The weird thing is that the Age tag with a 's' behind it DOES work ingame when the entity is an item.

I suggest removing the rule that there must be a certain character behind nbt tags, but it's your call ;)

**Screenshot:**
![image](https://user-images.githubusercontent.com/39121384/45744268-71322880-bbfe-11e8-819f-2b6d3a250616.png)

**Comment by 42iscool42** [comment]
I am going to keep the rule for the letter because I want to have stricter highlighting. I will take a look at the Age tag, however.

**Comment by DerpNerb** [comment]
Ah okay fine 👍
