### ISSUE TITLE
Error with NBT of empty chest

### ISSUE THREAD

**Issue by MattCM** [42iscool42/MCC#55]
Bug in Marshal Command Code

When entering a empty chest NBT it is highlighted as incorrect. This is part of an execute command.

Screenshot:
![image](https://user-images.githubusercontent.com/44980073/48732484-b642fd00-ec37-11e8-8382-c1e5ef8e586b.png)

Code:
execute if block -304 2 354 minecraft:chest{Items:[]} run setblock -304 2 354 minecraft:chest{Items:[{id:"bread",Slot:1b,Count:64b},{id:"bread",Slot:2b,Count:64b},{id:"bread",Slot:3b,Count:64b},{id:"bread",Slot:4b,Count:64b},{id:"bread",Slot:10b,Count:64b},{id:"bread",Slot:11b,Count:64b},{id:"bread",Slot:12b,Count:64b},{id:"bread",Slot:13b,Count:64b},{id:"bread",Slot:19b,Count:64b},{id:"bread",Slot:20b,Count:64b},{id:"bread",Slot:21b,Count:64b},{id:"bread",Slot:22b,Count:64b}]} destroy

I'm sure there is some sort of placeholder that is needed to go within the {Items:[]} but I'm new and not sure what it should be.

**Comment by 42iscool42** [comment]
This was an error with MCC not you.  That command is syntactically correct.  I will put out a new release now that has this fix.  It may take some time for package control to notice the new version and update.

**Comment by MattCM** [comment]
Can I force an update through package control?

**Comment by 42iscool42** [comment]
Yes, you can use ctrl + shift + p to open the command palette, then search for upgrade packages and hit enter.

**Comment by MattCM** [comment]
Found it, thanks for the pointers, this is all new to me but learning fast!
