### ISSUE TITLE
Block tags force use of "minecraft:"

### ISSUE THREAD

**Issue by DerpNerb** [42iscool42/MCC#56]
**Version:** Marshal Command Code v2.1.2
**Description:** The block tag syntax is inconsistent with the vanilla syntax, which allows tags without the minecraft: before.
**Screenshots:**
![image](https://user-images.githubusercontent.com/39121384/48734760-af6fb680-ec46-11e8-87e9-bcc8327b5dd9.png)
![image](https://user-images.githubusercontent.com/39121384/48734930-391f8400-ec47-11e8-9c14-ae9e644c7663.png)

**Comment by 42iscool42** [comment]
This has been fixed in the newest release.
