### ISSUE TITLE
"Execute if" is not allowed

### ISSUE THREAD

**Issue by DerpNerb** [42iscool42/MCC#57]
**Version:** Marshal Command Code v2.1.2
**Description:** In 1.13 the /testfor command got removed. What can be used instead is "execute if". The syntax only allows "execute if" if there is a command that follows.

**Screenshots:**
![image](https://user-images.githubusercontent.com/39121384/48735352-6b7db100-ec48-11e8-94d9-8560da0c69a5.png)
![image](https://user-images.githubusercontent.com/39121384/48735398-95cf6e80-ec48-11e8-973d-e87fc1d3fa44.png)

**Comment by 42iscool42** [comment]
This has been fixed in the newest release.
