### ISSUE TITLE
drowned mob not recognised within a target selector or summon command

### ISSUE THREAD

**Issue by MattCM** [42iscool42/MCC#59]
MCC issue

The drowned mob type does not seem to be recognised by MCC

![image](https://user-images.githubusercontent.com/44980073/48838229-adf5d980-ed7f-11e8-94ac-b29ae428f214.png)

![image](https://user-images.githubusercontent.com/44980073/48838266-c36b0380-ed7f-11e8-9947-59e6251299fb.png)

kill @e[type=drowned]
summon minecraft:drowned ~ ~ ~

**Comment by 42iscool42** [comment]
This has been fixed in the newest release.
