### ISSUE TITLE
Selectors within JSON don't play nice.

### ISSUE THREAD

**Issue by Moesh** [42iscool42/MCC#6]
Adding any arguments after the selector (i.e. @s[m=0]) makes it display fine(edited)

Example code:

Displays incorrectly, bracket highlights as errors
`title @a actionbar {"selector":"@s"}

Displays correctly, due to additional selector.
title @a actionbar {"selector":"@s[m=1]"}`

**Comment by Moesh** [comment]
![image](https://user-images.githubusercontent.com/4852592/27989205-4e03af3e-640a-11e7-80b6-61ecea5d709b.png)

This also seems to be causing some highlighting to break.

**Comment by 42iscool42** [comment]
Fixed.  Look for it in the release coming out later today.
