### ISSUE TITLE
Attribute syntax

### ISSUE THREAD

**Issue by MattCM** [42iscool42/MCC#60]
MCC issue

MCC makes correctly syntaxed mob attributes in NBT data as incorrect.

![image](https://user-images.githubusercontent.com/44980073/49248934-e007db00-f412-11e8-907b-d9906a37500d.png)

summon zombie ~ ~ ~ {Attributes:[{Name:"generic.followRange",Base:100.0}]}

**Comment by 42iscool42** [comment]
MCC requires a slightly stricter syntax in NBT in order to accurately highlight the values in NBT.  In this case, Base:100.0 needs to have the d suffix to tell MCC it is a double value.  You will need to do summon zombie ~ ~ ~ {Attributes:[{Name:"generic.followRange",Base:100.0d}]} instead.

**Comment by MattCM** [comment]
Thanks 42iscool42! I knew this and have been using the b suffix on other double values, silly me!
