### ISSUE TITLE
execute in breaks parser

### ISSUE THREAD

**Issue by SnaveSutit** [42iscool42/MCC#61]
Version affected: Marshal Command Code
Steps to reproduce: Write an execute command with `in` operator in it
Picture:
![image](https://user-images.githubusercontent.com/28514936/51335772-e862b680-1a50-11e9-9b58-55a28b637bc4.png)
It's difficult to tell from a picture because the highlighting doesn't update when I change the text unless I remove the `in minecraft:overworld` from the execute command
Code: `execute store result entity @e[tag=warp_entity,limit=1] Pos[0] double 1 run scoreboard players get @s home.z
execute if entity @s[scores={home.d=0}] in minecraft:overworld at @e[tag=warp_entity,limit=1] run tp @s ~ ~ ~
kill @e[tag=warp_entity]`

**Comment by 42iscool42** [comment]
While the parser is not actually crashing in this instance, it is marking it as incorrect code even though it is correct.  What color scheme are you using? The part that appears to be grey should be highlighting as red or whatever color incorrect code is highlighted as in your color scheme?

**Comment by SnaveSutit** [comment]
No, that's not the issue. That part was commented out and that's why it's gray, however when I remove the comment or add in `in` into the command ALL of the syntax of the entire file stops updating. If i add something else on any line after adding `in` to the command it appears white (not highlighted at all)

**Comment by 42iscool42** [comment]
I see now.  The problem was happening slightly differently on my machine.  Seems all is good with this now.
