### ISSUE TITLE
Unable to interpret resource locations for custom sound events in playsound

### ISSUE THREAD

**Issue by dominicsherry1** [42iscool42/MCC#62]
This bug affects Marshal Command Code.

It seems like there is a problem with interpreting resource locations in the playsound command which are not sound events in the default resource pack. For example, syntax highlighting works for the command

`playsound minecraft:ambient.underwater.loop ambient @s`

but does not work for the command

`playsound custom:ambient.underwater_bubbles ambient @s`

From the file “Parser.py” inside the sublime-package file the function sound_parser shows where the problem lies:

def sound_parser(self, properties={}):
                        return self.location_from_list_parser(self.regex["resource_location"], SOUNDS)

It seems like “SOUNDS” only contains a list of sound events included in the default resource pack.

**Comment by 42iscool42** [comment]
Sorry for the long time on response for this one, but a new version is out now that fixes this.
