### ISSUE TITLE
NBT data syntax does not support the NOT operator

### ISSUE THREAD

**Issue by dominicsherry1** [42iscool42/MCC#63]
This error occurs in Marshal Command Code, I have not tried MCFunction.

The command

`execute if entity @e[nbt={Key:Value}] run some:function`

works as intended, however

`execute if entity @e[nbt=!{Key:Value}] run some:function`

is highlighted as an error.

**Comment by 42iscool42** [comment]
Sorry for the long time on response for this one, but a new version is out now that fixes this.

**Comment by dominicsherry1** [comment]
Can confirm this is working properly now. Thanks for fixing.
