### ISSUE TITLE
Bad highlighting

### ISSUE THREAD

**Issue by Daminator4113** [42iscool42/MCC#64]
1. Hi, the problem is that some commands are highlighted like is bad, but they are correct.

2.  ![image](https://user-images.githubusercontent.com/43492665/53033806-2ac54c00-3472-11e9-886c-7b10eb55dc99.png)

3. `summon armor_stand ~ ~ ~ {ArmorItems:[{},{},{},{id:"minecraft:iron_helmet",Count:1b}]}`
`summon armor_stand ~ ~ ~ {ArmorItems:[{},{},{},{}]}`
`summon armor_stand ~ ~ ~ {Tags:["Something"]}`
`give @p stone{display:{Name:"{\"text\":\"123\"}"}}`
`give @p stone{display:{Lore:["123"]}}`
`tellraw @a {"text":"123","bold":true}`
`tellraw @a {"text":"123","bold":"true"}`
`advancement revoke @a only customs:noteblock/trigger/place_noteblock`
`setblock ~ ~ ~ minecraft:note_block[powered=false]`
`datapack disable "file/MyDatapack"`

**Comment by Daminator4113** [comment]
I'm sorry, I don't know how to mark an issue as bug or something else ^^'

**Comment by 42iscool42** [comment]
For me, the fourth and fifth lines are highlighting correctly.  Are you sure you are on the newest version?  The other ones are still highlighting incorrectly, so I will look at those.  You can upgrade packages by hitting ctrl + shift + p and then searching for upgrade package.

**Comment by Daminator4113** [comment]
Thank you for responding, then yes I am on the last version of the package and the commands are in 1.13.2
The 4th and 5th lines are correct and should not be highlighted.
![image](https://user-images.githubusercontent.com/43492665/53043270-63702000-3488-11e9-898b-7e34d3a83586.png)

`give @p stone{display:{Name:"Hello"}}`
`give @p stone{display:{Name:"\"Hello\""}}`
`give @p stone{display:{Name:"{\"text\":\"Hello\"}"}}`
`give @p stone{display:{Lore:["Hello"]}}`

**Comment by 42iscool42** [comment]
Technically that first command is still valid and so is correctly highlighted even though it doesn't really do what is expected.  Also, on my install, all four of those are highlighted correctly
![Correctly Highlighted Commands Screenshot](https://imgur.com/3qevo0D.png)

Can you run the "list packages" command from the command pallete (ctr + shift + p) and tell me which version of MCC it says is installed?

**Comment by Daminator4113** [comment]
![image](https://user-images.githubusercontent.com/43492665/53053276-3714cd80-34a1-11e9-93a0-273e57289e1d.png)

**Comment by 42iscool42** [comment]
It appears you have a manually installed version as well as the version installed from package control.  If you remove the manually installed one that should fix some of the issues and I am currently working on fixing the rest.

**Comment by 42iscool42** [comment]
I just put out a release that fixes the highlighting issues.  To delete the manual install, you should go to Preferences->Browse Packages and then delete the MCC folder in there.  That should fix the rest of your problems.

**Comment by Daminator4113** [comment]
This doesn't work, I have tried to remove the package and reinstall it, or delete only MCC folder, etc... But nothing work :/

If I delete the MCC folder, it happening this :
![image](https://user-images.githubusercontent.com/43492665/53054649-4eee5080-34a5-11e9-9e89-7f6bc7ed7e29.png)

And if I change the color scheme, it recreated an MCC folder, and go back to this :
![image](https://user-images.githubusercontent.com/43492665/53054757-b5736e80-34a5-11e9-99bf-a706dfddfecd.png)

I don't know why it doesn't work with me, maybe I do something wrong ?

**Comment by 42iscool42** [comment]
I'm not entirely sure what's wrong.  I thought you had MCC installed locally but I forgot the plugin generates files in there as well.  Can you try running upgrade packages again and see if that fixes it?

**Comment by Daminator4113** [comment]
always not
![image](https://user-images.githubusercontent.com/43492665/53055076-c1136500-34a6-11e9-8b8b-c352fbc3ae5c.png)
![image](https://user-images.githubusercontent.com/43492665/53055107-de483380-34a6-11e9-9a08-81eabfaeb348.png)

**Comment by Daminator4113** [comment]
I think I have found the problem, but I don't understand why it's happening,
I have tried to create an other files with same commands, to see what's happening, and it work! But the old files stil doesn't work, whatever I'm doing

![image](https://user-images.githubusercontent.com/43492665/53055221-32ebae80-34a7-11e9-9efe-e72d9b70374d.png)

**Comment by 42iscool42** [comment]
Is this the entirety of the file? Does it work if you directly copy paste this file into another one?

**Comment by Daminator4113** [comment]
I understand nothing, in my file there are normally other commands before, and I only copied the lines for the examples (give commands). All alone these lines are not highlighted, but with the rest of the file, they are again.

Even worse, if I open the file "uncorrupted" alone, the lines are not highlighted.
But if I open the file "corrupted", and the uncorrupted file is open, the lines will be highlighted in the two files

**Comment by Daminator4113** [comment]
I think I have found the problem, there is only one command who "corrupts" the files.

**Comment by 42iscool42** [comment]
Which command?

**Comment by Daminator4113** [comment]
She's big, I'll going to try to find what nbt tag do all of that.

**Comment by 42iscool42** [comment]
If you have problems finding the problem, send me the whole thing.  I can look through it myself.

**Comment by Daminator4113** [comment]
Ok, there is the command : `give @p written_book{pages:["{\"text\":\"TEST\"}"]}`

**Comment by Daminator4113** [comment]
While you're there, I think I've found another bug, should I create a new issue ?

**Comment by 42iscool42** [comment]
Yes

**Comment by Daminator4113** [comment]
I found new commands who doesn't work correctly : 
`give @a bow{Enchantments:[{lvl:1s,id:"minecraft:infinity"}]}`
`scoreboard objectives add Death deathCount`
`bossbar add test {"text":"BOSSBAR"}`
Structure block : `data merge block ~ ~ ~ {name:"minecraft:test"}`
Sign : `data merge block -15 4 0 {Text2:"{\"text\":\"Hi\"}"}`

This one completely disables the highlighting : 
`tellraw @a {"text":"TEST","hoverEvent":{"action":"show_text","value":"HELLO"}}`

**Comment by dominicsherry1** [comment]
>     * `give @a bow{Enchantments:[{lvl:1s,id:"minecraft:infinity"}]}`

I notice an issue with a similar command as well. The problem seems to be that the syntax highlighting doesn't know what to do with the `s` in `lvl:1s`.
For reference, the command I am having trouble with is `execute as @s[nbt={SelectedItem:{tag:{Enchantments:[{id: "minecraft:fortune", lvl: 1s}]}}}] if block ~ ~ ~ minecraft:nether_quartz_ore if score rng rand matches ..66 run summon minecraft:item ~ ~ ~ {Item:{id: "minecraft:quartz", Count: 1b}}`

**Comment by 42iscool42** [comment]
Sorry for the long delay on this one, but I have been pretty busy the past month or so.  These are now fixed in the newest release.
