### ISSUE TITLE
Unable to import with Sublime 3 on Linux

### ISSUE THREAD

**Issue by CubeTheThird** [42iscool42/MCC#66]
While I don't necessarily expect this issue to be addressed here, I figure it would at least be worth documenting. This is in part the result of an upstream problem:

cProfile cannot be imported on Linux
https://github.com/SublimeTextIssues/Core/issues/127

Seems other projects have developed workarounds, and as the report has existed for 6 years now, I don't expect it will be fixed any time soon.

**Comment by 42iscool42** [comment]
Does this prevent the highlighter from working entirely?  The part that does use cProfile is not intended for general use so I don't really care if it works for everyone or not.

**Comment by CubeTheThird** [comment]
Yes, this prevents the plugin from being able to load, resulting in the following stacktrace:

[stacktrace.txt](https://github.com/42iscool42/MCC/files/3182531/stacktrace.txt)

Nice to know that it isn't as impactful as I expected.

**Comment by 42iscool42** [comment]
The latest release has removed the offending file, so now everything should work fine on Linux.
